"""add abgeschlossen to gruppe

Revision ID: 246c1fbe7c2f
Revises: b4824649e40b
Create Date: 2026-06-03 20:27:25.424492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c1fbe7c2f'
down_revision = 'b4824649e40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gruppe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abgeschlossen', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gruppe', schema=None) as batch_op:
        batch_op.drop_column('abgeschlossen')

    # ### end Alembic commands ###
