"""add vertraulichkeit gruppengroesse to kategorie

Revision ID: 697401039325
Revises: 305239d97ba3
Create Date: 2026-06-03 20:53:49.132891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697401039325'
down_revision = '305239d97ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vertraulichkeit', sa.Enum('OFFEN', 'INTERN', 'VERTRAULICH', name='vertraulichkeit'), nullable=True))
        batch_op.add_column(sa.Column('gruppengroesse', sa.Enum('ALLEIN', 'KLEIN', 'MITTEL', 'GROSS', name='gruppengroesse'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategorie', schema=None) as batch_op:
        batch_op.drop_column('gruppengroesse')
        batch_op.drop_column('vertraulichkeit')

    # ### end Alembic commands ###
