"""initial schema

Revision ID: b4824649e40b
Revises: 
Create Date: 2026-06-03 16:41:10.056460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4824649e40b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gruppe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zeitraum_von', sa.Date(), nullable=False),
    sa.Column('zeitraum_bis', sa.Date(), nullable=False),
    sa.Column('sharing_ratio', sa.Float(), nullable=False),
    sa.Column('registrierung_link_token', sa.String(length=64), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registrierung_link_token')
    )
    op.create_table('raumtyp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('rolle', sa.Enum('ADMIN', 'TEILNEHMER', name='rolle'), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('pin_temporaer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('einreichung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OFFEN', 'EINGEREICHT', 'IN_BEARBEITUNG', 'ABGESCHLOSSEN', name='einreichungstatus'), nullable=False),
    sa.Column('eingereicht_am', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gruppe_id', name='uq_einreichung_user_gruppe')
    )
    op.create_table('gruppen_mitglied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gruppe_id', name='uq_user_gruppe')
    )
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('farbe', sa.String(length=7), nullable=True),
    sa.Column('raumtyp_id', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raumtyp_id'], ['raumtyp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('kategorie_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('zeit_von', sa.Time(), nullable=False),
    sa.Column('zeit_bis', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppe.id'], ),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eintrag')
    op.drop_table('kategorie')
    op.drop_table('gruppen_mitglied')
    op.drop_table('einreichung')
    op.drop_table('user')
    op.drop_table('raumtyp')
    op.drop_table('gruppe')
    # ### end Alembic commands ###
